spring:
  application:
    name: wayne-ai-agent
  ai:
    dashscope:
      api-key: sk-6fa01b0780474b46b2d332347efc14aa
      chat:
        options:
          model: qwen-plus
  #    vectorstore:
  #      pgvector:
  #        index-type: HNSW
  #        dimensions: 1536
  #        distance-type: COSINE_DISTANCE
  #        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
  #        initialize-schema: true
  datasource:
    url: jdbc:postgresql://pgm-uf6d10u6v55lk9a0po.rwlb.rds.aliyuncs.com/ai_agent
    username: ai_agent
    password: 1qazxsw2A
knife4j:
  enable: true
  setting:
    language:en

# searchAPI
search-api:
  api-key: RNcL8tMhbu2VfkR4nE8Pv8ji
  logging:
  level:
    org.springframework.ai: DEBUG
